sudo: false  
language: java    
jdk:
  - oraclejdk8
cache:  
  directories:  
   - $HOME/.m2
before_install: ./setup_travis.sh
script: "./mvnw package -B"
deploy:
  skip_cleanup: true
  provider: bintray
  file: "deploy.json"
  user:
      secure: "ky74f816T4PopnSyysrW7eiOieIV1LFNW7Oj8zC54dJvNiS+zFPa8QVT7RsfEK4oYa5Fac5Tzvvgq6peYu6X2rJK49Y8S/XP0oTNOrjdUvOKixMHLy/sb8a5JrHFp5xZck7MIL3E04pIgQYFt00eIIozk7iZ70Fw1rlrnDeA0YOIvBK4cUK4WFfUO4YsndBpcRUgOqh/erSzlcSeFHRfsDbe/f7yWO7GnjDCkhNE0V/wYsh4omz99RmkkxHXWdsiBKxPOUsXIfCjA/ZACIWSOO9XsWeVRvI0MVVIBmim38N2oS5R9dEI9tvHmuVp9/KcNSjc1YnKSzxqIc5yW0fGgfnhk1rHUVUcRlpDs2pwIad9xiDwWzHt9QTnC1F/a9lAoDOUCSTZaKLvEoDGi6ZTOfJKXbynCS8GbRWlhyTrRHaeCyHgYPyYGR9/OjM3Ok7GK7D67R2zdcBqXScxx0XQ1mJLY/MscIEoQ1ufvWRhEKwHiqFuS6UGyhcDk6tTdd5N6mn7EuodSun/50ulgRArGB0vyxuNPyKstM99fdxXniQZPWIQ23rmaNEmNlsY4WHFyG/9/HIIMEpH8OaJ6c/N+I2ZvECHYdTHaM8LT9B8//DBhGQSWgMsUyduEQt3Ag6rImZbcGKMJ2t87t52LYj6VAqFkT5vy5RkOvuNzpnrOwk="
  key:
      secure: "jMLymMdcMU3LKYRYixXeB+zV+Q8Dlk2CnWMmKGodJey+j4+vXsTQAbxGdHCmruTWeeUAGDCLjO1K4owDbt6XYL8xUgANJcAhA6ZKk23QWSTVI0BeRzm0TpW56OBAAtyZ8CZE9ZwF5FSYBc21pouLIDio+vbfVDqjoNuTVfypz6rFMMzF7zdGhNM5mWLrO+pF4XHGEzTm8VHMqc+fUOlXA6S8UM2rAfC4w4qeq3r6VIEZ99Ep1Cn7oVbnITX0R7tZMQ9wPs8hUF7YaNTjIjjS1IKahDjQHl6wsbhFyRbE2CH2502AJRGvRwdOM0RSiV96ysu6XaqELyP7WsbBLdghiFYojVz8n4NsSV767FwJGXc8yxd5iwjd6JuhwzgFA5hBj6AN1ZVoaSZDovj89oveIcHz9N1TlUp+YyeCUGRwxjMLpvpr/Ect60S/aJcbuBkh5eBWNT0wU+A4LzrGsC1WkrohaFexbt8gMbag6zz+CKcSml23knPk7dZEVY9GpueSfOrTxWn1lozis/r74yW//2N5CzUwvubQPxUzCNkVl2UVww6v2yCbGt/g/neE90luOvfuI0Z+bS5OWVpMDjd/BIusmHROti8wkYQz+8PgT0HWomW/0PjX+6Ra6O2SElLdzyITwFtP0GM6uO9B8Z9kRjEFsxeWTSIp9VEIRKRhhRU="
